const paths = {
  PUBLIC: "",
  HOME: "/",
  LOGIN: "/login",
  ALBUM: "/album/:title/:id",
  PLAYLIST: "/playlist/:title/:id",
  WEEKCHART: "/zing-chart-tuan/:title/:id",
  ZINGCHART: "/zing-chart",
  NEWRELEASE: "/moi-phat-hanh",
  RADIO: "/radio",
  AllRESULT: "/tim-kiem/tat-ca",
  SONGS: "/tim-kiem/bai-hat",
  PLAYLISTSEARCH: "/tim-kiem/playlist",
  MVSEARCH: "/tim-kiem/video",
  ARTISTSEARCH: "/tim-kiem/artist",
  MUSICIER: "/nghe-si/:singer",
  FAVORITE: "/mymusic",
  FAVORITESONG: "/mymusic/song",
  FAVORITEPLAYLIST: "/mymusic/album",
  FAVORITEMV: "/mymusic/mv",
  MYLIBRARY: "/mymusic/library",
  MYPLAYLIST: "/mymusic/library/playlist",
  MYOWNPLAYLIST: "/mymusic/library/playlist/owner",
  HISTORY: "/mymusic/history",
  HISTORYSONG: "/mymusic/history/song",
  HISTORYPLAYLIST: "/mymusic/history/playlist",
  HISTORYMV: "/mymusic/history/video",
  HUB: "/hub",
  HUBDETAIL: "/hub/:title/:id",
  TOP100: "/top100",
  VIDEO: "/video-clip/:title/:id",
};
export default paths;
